### ISSUE TITLE
Default latex definitions

### ISSUE THREAD

**Issue by DancingQuanta** [ickc/pandoc-amsthm#3]
I have been writing plenty of maths and physics docs and I liked this filter and wanted to use it.
However what I do not like is to use the YAML block repeatedly in my every document.

I wonder if it is possible for the current YAML block specified in the README to be set as default in the filter in order to remove the need to define the environments in YAML of every document I write.
And since the defaults are set, it should be possible to override them within the YAML block.

But good job!

**Comment by ickc** [comment]
Hi, @DancingQuanta 

Sorry for the late reply.

I think the easier and more flexible way to accomplish what you asked is this:

- Create a `amsthm-default.md` containing:

```yaml
---
amsthm:
  plain:    [Theorem]
  plain-unnumbered: [Lemma, Proposition, Corollary]
  definition:   [Definition,Conjecture,Example,Postulate,Problem]
  definition-unnumbered:    []
  remark:   [Case]
  remark-unnumbered:    [Remark,Note]
  proof:    [proof]
  parentcounter:    chapter
...
```

- For any of the pandoc md you want to build, add that template like this:

```bash
# say your command was this
pandoc -s -o test.pdf test.md
# it becomes
pandoc -s -o test.pdf /pathto/amsthm-default.md test.md
```

This should work even if `test.md` has its own YAML, because pandoc would

1. `cat` the given list of md
2. allow multiple YAML throughout the documents.

Personally, I wrote a small bash script for the build commands I used most, e.g. [this one](https://github.com/ickc/pandoc-scripts/blob/master/build/panpdf.sh). So I would just insert the template there.

Let me know if what I say works for you. If it is useful, I probably would add it in the readme as an example.
